# -*- coding: utf-8 -*-
"""Sample Project Rundown

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdhGZB6RVuR6KUvKPHY9umN6xVLAjv4j
"""

# These are terminal commands to install dependencies
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
!pip install nnunetv2 nibabel numpy matplotlib

# We then get the patient data
from google.colab import files
uploaded = files.upload()

# Unzip patient data
!unzip "Patient Files.zip" -d /content/data

# We set up our environment variables and create the correct folders
import os

os.environ["nnUNet_raw"] = "/content/nnUNet/nnUNet_raw"
os.environ["nnUNet_preprocessed"] = "/content/nnUNet/nnUNet_preprocessed"
os.environ["nnUNet_results"] = "/content/nnUNet/nnUNet_results"

!mkdir -p /content/nnUNet/nnUNet_raw/Dataset501/imagesTr
!mkdir -p /content/nnUNet/nnUNet_raw/Dataset501/labelsTr
!mkdir -p /content/nnUNet/nnUNet_raw/Dataset501/imagesTs


# we looking isde the patient folders and scan the MRI files for MRI modality name. Then we rename them according to the channel code given by nnU-Net
import os, shutil, re

data_root = "/content/data"
target_imagesTr = "/content/nnUNet/nnUNet_raw/Dataset501/imagesTr"

for case_folder in os.listdir(data_root):
    case_path = os.path.join(data_root, case_folder)
    if not os.path.isdir(case_path):
        continue

    case_id = case_folder

    for file in os.listdir(case_path):
        if "flair.nii.gz" in file.lower():
            channel = "0000"
        elif "t1.nii.gz" in file.lower() and "t1gd" not in file.lower():
            channel = "0001"
        elif "t1gd.nii.gz" in file.lower() or "t1gd" in file.lower():
            channel = "0002"
        elif "t2.nii.gz" in file.lower():
            channel = "0003"
        else:
            continue

        src = os.path.join(case_path, file)
        dest = os.path.join(target_imagesTr, f"{case_id}_{channel}.nii.gz")

        shutil.copy(src, dest)
        print("Copied:", dest)

# Finds the best/cleaned segmentation mask file for each case, specifically the one containing "ManuallyCorrected" in the name.
target_labelsTr = "/content/nnUNet/nnUNet_raw/Dataset501/labelsTr"

for case_folder in os.listdir(data_root):
    case_path = os.path.join(data_root, case_folder)
    case_id = case_folder

    for file in os.listdir(case_path):
        if "manuallycorrected.nii.gz" in file.lower():
            src = os.path.join(case_path, file)
            dest = os.path.join(target_labelsTr, f"{case_id}.nii.gz")
            shutil.copy(src, dest)
            print("Label Copied:", dest)



# Builds a dataset config dictionary
import json, os

dataset = {
    "channel_names": {
        "0": "FLAIR",
        "1": "T1",
        "2": "T1GD",
        "3": "T2"
    },
    "labels": {
        "background": 0,
        "tumor": 1
    },
    "numTraining": 5,
    "file_ending": ".nii.gz",
}

save_path = "/content/nnUNet/nnUNet_raw/Dataset501/dataset.json"
os.makedirs(os.path.dirname(save_path), exist_ok=True)

with open(save_path, "w") as f:
    json.dump(dataset, f, indent=4)


# Binarizes files for easy sample training

import os
import nibabel as nib
import numpy as np

labels_dir = "/content/nnUNet/nnUNet_raw/Dataset501/labelsTr"

for file in os.listdir(labels_dir):
    if not file.endswith(".nii.gz"):
        continue

    path = os.path.join(labels_dir, file)
    img = nib.load(path)
    data = img.get_fdata()

    # Binarize: convert all tumor regions into 1
    data[data > 0] = 1

    # Save back, overwrite file
    new_img = nib.Nifti1Image(data, img.affine, img.header)
    nib.save(new_img, path)
    print("Binarized:", file)


# Verifies data and creates training plans
!nnUNetv2_plan_and_preprocess -d 501 --verify_dataset_integrity

# Verifies that the last command ran successfully
!ls /content/nnUNet/nnUNet_preprocessed

!ls /content/nnUNet/nnUNet_preprocessed/Dataset501

# Trains the 2D segmentation model
!nnUNetv2_train 501 2d 0 --npz


# Moves the test scans into the proper directory
import os, shutil

src_root = "/content/data"
ts_root = "/content/nnUNet/nnUNet_raw/Dataset501/imagesTs"
os.makedirs(ts_root, exist_ok=True)

for case in os.listdir(src_root):
    case_dir = os.path.join(src_root, case)
    if not os.path.isdir(case_dir):
        continue

    for fname in os.listdir(case_dir):
        lower = fname.lower()
        if "flair.nii.gz" in lower:
            ch = "0000"
        elif "t1gd.nii.gz" in lower or "t1gd" in lower:
            ch = "0002"
        elif lower.endswith("t1.nii.gz") and "t1gd" not in lower:
            ch = "0001"
        elif "t2.nii.gz" in lower:
            ch = "0003"
        else:
            continue

        src = os.path.join(case_dir, fname)
        dst = os.path.join(ts_root, f"{case}_{ch}.nii.gz")
        shutil.copy(src, dst)
        print("Copied:", dst)

print("All test scans copied into imagesTs ✅")

# Loads 2D segmention from fold 0 and runs MRI inference 
!nnUNetv2_predict -d 501 -c 2d -f 0 \
  -i /content/nnUNet/nnUNet_raw/Dataset501/imagesTs \
  -o /content/preds \
  -chk checkpoint_best.pth \
  --disable_tta --verbose

# Selects a specific patient case and loads the FLAIR MRI scan and the predicted tumour segmention mask for viewing
import nibabel as nib
import matplotlib.pyplot as plt
import numpy as np

case = "TCGA-CS-5397" # change this to any case in Dataset501

img = nib.load(f"/content/nnUNet/nnUNet_raw/Dataset501/imagesTs/{case}_0000.nii.gz").get_fdata()
mask = nib.load(f"/content/preds/{case}.nii.gz").get_fdata().astype(np.uint8)

# Show 3 slice views: center, ±10
slice_idx = img.shape[2] // 2
for i in [slice_idx-10, slice_idx, slice_idx+10]:
    plt.imshow(img[:,:,i])
    plt.imshow(mask[:,:,i], alpha=0.4)
    plt.axis("off")
    plt.title(f"Overlay slice {i}")
    plt.show()